spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      connection-timeout: 10000
      initialization-fail-timeout: 10000

server:
  port: 8080

logging:
  level:
    com.shl.payment: INFO
    com.zaxxer.hikari: DEBUG
